config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "logs#index"
  resources :caffes, only: [:index] do
    resources :logs, only: [:new, :create, :destroy] 
      collection do
      get 'all' => 'logs#all'
      end
    end  
  resources :users, only: [:show, :edit, :update]
  resources :maps, only: [:index]
  # ↓簡易ログイン用
   devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caffe.rb
class Caffe < ApplicationRecord
    has_many :logs
    has_many :users, through: :logs
    # logsテーブルを通すとusers,caffesは多対多
end

app/models/log.rb
class Log < ApplicationRecord
    belongs_to :caffe
    belongs_to :user
    
    scope :created_today, -> { where("created_at >= ?", Time.zone.now.beginning_of_day) }
    # phpmyadminではcreated_atがイギリス時間になっているがコンソールから日本時間になっていることを確認
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :nickname, presence: true
  # ニックネームを必ず入力させる
  has_one_attached :image
  has_many :logs
  has_many :caffes, through: :logs
  # logsテーブルを通すとusers,caffesは多対多
  
  # ↓簡易ログイン用
  def self.guest
    find_or_create_by!(email: 'guest@com', nickname: 'guest') do |user|
    user.password = SecureRandom.urlsafe_base64
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    protect_from_forgery with: :exception
    # CSRF対策(クロスサイトリクエストフォージェリ)アクセスしたユーザーに対して意図しない操作を行わせないため
    
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_out_path_for(resource)
        "/users/sign_in"
    end
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :image])
    end

end

app/controllers/caffes_controller.rb
class CaffesController < ApplicationController
    
    def index
        redirect_to :root and return    
    end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
    
     before_action :authenticate_user!, except: [:index, :all]
    
    def index
    
        if user_signed_in?
            c_id = Log.created_today.where(user_id: current_user.id).pluck(:caffe_id)
                        # created_todayはlog.rbに定義
            caffeine = c_id.map{|id| Caffe.find(id).caffeine_mg}
            @today_caffeine = caffeine.sum
        end
        
    end
    
    def all
        @logs = Log.page(params[:page]).per(6).order("created_at DESC")
    end
    
    def new
        @caffe = Caffe.find(params[:caffe_id])
        @log = Log.new
        @suji = @caffe.id.to_i
    end
    
    def create
       Log.create(create_params)
    end

    def destroy
        @caffe = Caffe.find(params[:caffe_id])
        @log = @caffe.logs.find(params[:id])
        @log .destroy
    end
    
    private
    
    def create_params
        params.require(:log).permit(:text).merge(caffe_id: params[:caffe_id], user_id: current_user.id) 
    end
    
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
    def index
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice:  "ゲストとしてログインしました!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        today = Log.created_today.where(user_id: current_user.id)
        @today = today.count
        c_id = today.pluck(:caffe_id)
        caffeine = c_id.map{|id| Caffe.find(id).caffeine_mg}
        @today_caffeine = caffeine.sum
        @logs = Log.where(user_id: current_user.id).order("created_at DESC")
        @cups = Log.where(user_id: current_user.id).count
    end
    
    def edit
    end
    
    def update
        current_user.update(update_params)
    end
    
    private
    
    def update_params
        params.require(:user).permit(:image, :nickname)    
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caffes_helper.rb
module CaffesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang ='ja'>
  <head>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
      <title>CaffeineWith<%= yield :title %></title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application',  'data-turbolinks-track': 'reload' %>
      <%= favicon_link_tag 'favicon.ico'%>
    </meta>
  </head>

  <body>
    <header class="header">
      <%= link_to "CaffeineWith", root_path, class: "homelogo" %>
      <div class="flash"><%= flash[:notice] %></div>
      
      <input type="checkbox" class="openSidebarMenu" name="check" id="openSidebarMenu">
      <label for="openSidebarMenu" class="sidebarIconToggle">
        <div class="spinner diagonal part-1"></div>
        <div class="spinner horizontal"></div>
        <div class="spinner diagonal part-2"></div>
      </label>
      
      <div id="sidebarMenu">
        <p>Menu</p>
        <div class="sidebarMenuInner">
          <%= link_to "Home", root_path, class: "innerlink" %>
          <%= link_to "Everyone's log", all_caffes_path, class: "innerlink" %>
          <% if user_signed_in? %>
            <%= link_to "My page", user_path(current_user), class: "innerlink" %>
            <%= link_to "Edit profile", edit_user_path(current_user), class: "innerlink" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "innerlink" %>
          <% else %>
            <%= link_to "Log in", new_user_session_path, class: "innerlink" %>
            <%= link_to "Sign up", new_user_registration_path, class: "innerlink" %>
            <%= link_to "Guest log in(企業様はこちら)", users_guest_sign_in_path, method: :post, class: "innerlink" %>
          <% end %>
            <%= link_to "Map of nearby cafes", maps_path, class: "innerlink" %>
        </div>
      </div>
    </header>
      
      <%= yield %>
    
    <footer>
      <p><a href="https://pixabay.com/ja/users/Madun_Digital-283126/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=393954" target="_blank" rel="noopener noreferrer">Madun Digital</a>さんによる<a href="https://pixabay.com/ja/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=393954" target="_blank" rel="noopener noreferrer">Pixabayからの画像</a></p>
    </footer>
    <!--<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%#= ENV['API_KEY'] %>&language=ja&libraries=places&callback=initMap"></script>-->
      <!--↑views/maps/index-->
  </body>
</html>

app/views/logs/_log.html.erb
<!--render => logs/all.html.erb users/show.html.erb-->
<div class="one-log">
    <p class="name"><%= log.user.nickname %><span class="ago">(<%= time_ago_in_words(log.created_at) %>前)</span></p>
    <p><%= log.text.truncate(74) %></p>
    <!--74文字以上の場合末尾に...をつけ省略-->
    <p class="strftime"><%= log.created_at.strftime('%m/%d %H:%M') %></p>
    
    <% if user_signed_in? && log.user_id == current_user.id %>
        <%= link_to image_tag("trash.png", class: "one-destroy"), caffe_log_path(log.caffe_id, log), method: :delete %>
        <%#= link_to "destroy this log", caffe_log_path(log.caffe_id, log), method: :delete, class: "one-destroy" %>
                                        <!--"/caffes/#{log.caffe_id}/logs/#{log.id}"と同義-->
    <% end %>                                  
</div>

app/views/logs/all.html.erb
<% provide :title, " | 記録一覧" %>
<div class="setting">
 <div class="whitecover">
  <div class="full">
   <%= render partial: "log", collection: @logs %>
    <div class="pagination">
     <%= paginate @logs %>
    </div>
  </div>
 </div>
</div>

app/views/logs/create.html.erb
<div class="bulletin">
    <div class="mini">
            <p>記録しました!<p>
            <%= link_to "トップページに戻る", root_path, class: "minibtn" %>
            <%= link_to "ログ一覧を見る", all_caffes_path, class: "minibtn" %>
    </div>
</div>

app/views/logs/destroy.html.erb
<div class="bulletin">
    <div class="mini">
            <p>ログを削除しました!<p>
            <%= link_to "トップページに戻る", root_path, class: "minibtn" %>
            <%= link_to "ログ一覧に戻る", all_caffes_path, class: "minibtn" %>
    </div>
</div>

app/views/logs/index.html.erb
<main class="main">
    <div class="maincontent">
        <div class="wrapper">
            <div class="btn">
                <%= image_tag '115815.png', class: "button" %>
            </div>
            <div class="explanation">
                <p>このwebアプリケーションはあなたのカフェイン摂取量が400mg/日を超えた時に摂取の抑制を促します</p>
                <p>コーヒーなどを飲む際に上のボタンを押してください!</p>
                <p>またコーヒーなどのを飲む際の感想などを記録、投稿することができます</p>
                <% if user_signed_in? && @today_caffeine >= 400 %>
                    <p class="emergency">今日はカフェインを400mg以上摂取しているため気を付けてください!</p>
                <% end %>
                <p>This web application helps reduce your caffeine intake when it exceeds 400 mg / day.</p>
                <p>Please press the button above when drinking coffee etc.!</p>
                <p>You can also record and post your impressions when drinking coffee etc.</p>
                <% if user_signed_in? && @today_caffeine >= 400 %>
                    <p class="emergency">Be careful as you are taking over 400mg of caffeine today!</p>
                <% end %>
            </div>   
        </div>
<!--jQueryで切り替わり---------------------------------------------------------------------------------------------------------------------------------            -->
        <div class="select">
            <div class="explanation xxx">
                <div class="choose">
                <p>お店と飲み物のサイズを選択してください</p>
                <p> Please choose a store and drink size.</p>
                </div>
            </div>
            <div class="items">
                <div class="eggs">
                    <div class="item">
                        <p class="starbucks">Starbucks Coffee</p>
                        <h3>-size-</h3>
                        <div class="size wid">
                        <div class="scroll-contents">
                            <%= link_to "short", new_caffe_log_path(1), class: "sbtn starbucks" %>
                            <%= link_to "tall", new_caffe_log_path(2), class: "sbtn starbucks" %>
                            <%= link_to "grande", new_caffe_log_path(3), class: "sbtn starbucks" %>
                            <%= link_to "venti", new_caffe_log_path(4), class: "sbtn starbucks" %>
                        </div>
                        </div>
                    </div>
                    <div class="item">
                        <p class="doutor">DOUT<span>O</span>R</p>
                        <h3>-size-</h3>
                        <div class="size">
                            <%= link_to "S", new_caffe_log_path(5), class: "sbtn doutor" %>
                            <%= link_to "M", new_caffe_log_path(6), class: "sbtn doutor" %>
                            <%= link_to "L", new_caffe_log_path(7), class: "sbtn doutor" %>
                        </div>
                    </div>
                    <div class="item">
                        <p class="tullys">TULLY's</p>
                        <h3>-size-</h3>
                        <div class="size wid">
                        <div class="scroll-contents">
                            <%= link_to "short", new_caffe_log_path(8), class: "sbtn tullys" %>
                            <%= link_to "tall", new_caffe_log_path(9), class: "sbtn tullys" %>
                            <%= link_to "grande", new_caffe_log_path(10), class: "sbtn tullys" %>
                            <%= link_to "enorme", new_caffe_log_path(11), class: "sbtn tullys" %>
                        </div>
                        </div>
                    </div>
                </div>
                <div class="eggs">
                    <div class="item">
                        <p class="excelsior"><span>E</span>XCELSIOR <span>C</span>AFFE</p>
                        <h3>-size-</h3>
                        <div class="size">
                             <%= link_to "S", new_caffe_log_path(12), class: "sbtn excelsior" %>
                             <%= link_to "M", new_caffe_log_path(13), class: "sbtn excelsior" %>
                             <%= link_to "L", new_caffe_log_path(14), class: "sbtn excelsior" %>
                        </div>
                    </div>
                    <div class="item">
                        <p class="other">その他</p>
                        <h3>-size-</h3>
                        <div class="size">
                            <%= link_to "S", new_caffe_log_path(15), class: "sbtn other" %>
                            <%= link_to "M", new_caffe_log_path(16), class: "sbtn other" %>
                            <%= link_to "L", new_caffe_log_path(17), class: "sbtn other" %>
                        </div>
                    </div>
                    <div class="item">
                        <P class="house">お家</p>
                        <h3>-size-</h3>
                        <div class="size">
                            <%= link_to "M", new_caffe_log_path(18), class: "sbtn house" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</main>

app/views/logs/new.html.erb
<div class="cover">
    <div class="sheet">
        <%= form_for [@caffe, @log] do |f| %>
            <!--選んだ店により文字色と背景を変える-->
            <% if @suji <= 4  %>
                <p><span class="starbucks"><%= @caffe.store %></span>で<span class="starbucks"><%= @caffe.size %></span>サイズのコーヒーを飲むことを記録します!</p>
                
            <% elsif @suji >= 5 && @suji <= 7  %>
                <p><span class="doutor"><%= @caffe.store %></span>で<span class="doutor"><%= @caffe.size %></span>サイズのコーヒーを飲むことを記録します!</p>
                
            <% elsif @suji >= 8 && @suji <= 11  %>
                <p><span class="tullys"><%= @caffe.store %></span>で<span class="tullys"><%= @caffe.size %></span>サイズのコーヒーを飲むことを記録します!</p>
                
            <% elsif @suji >= 12 && @suji <= 14 %>
                <p><span class="excelsior"><%= @caffe.store %></span>で<span class="excelsior"><%= @caffe.size %></span>サイズのコーヒーを飲むことを記録します!</p>
                
            <% elsif @suji >= 15 && @suji <= 17 %>
                <p><span class="other"><%= @caffe.store %></span>で<span class="other"><%= @caffe.size %></span>サイズのコーヒーを飲むことを記録します!</p>
                
            <% else %>
                <p><span class="house"><%= @caffe.store %></span>で<span class="house"><%= @caffe.size %></span>サイズのコーヒーを飲むことを記録します!</p>
            <% end %>
            
            <%= f.text_area :text, placeholder: "コーヒーを飲んだ時の感想,思いついたことなど自由に書き込んでみましょう!", class: "text-area" %>
            <div class="newbtnwrapp">
                <%= f.submit "記録する", class: "newbtn" %>
            </div>
        <% end %>
    </div>
</div>

app/views/maps/index.html.erb
<div class="setting map-cover">
    <h3 class="caffes-map">Caffes map<span>(現在地から半径750m以内にあるカフェを表示しています/Showing cafes within a radius of 750m from your current location)</span></h3>
    <div id='map'></div>
</div>

<!--↓ You have included the Google Maps API multiple times on this pageエラーの回避策-->
<script>
      if(window.google) {
        initMap();
      } else {
        $.ajax("https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&language=ja&libraries=places&callback=initMap", {
        crossDomain: true,
        dataType: 'script'
        });
      }
</script>

app/views/users/edit.html.erb
<% provide :title, " | ユーザー情報編集" %>
<div class="editpage">
    <div class="editcard">
        <%= form_for current_user do |f| %>
            <div class="info">
              <h3>イメージ画像</h3>
              <%= f.label :image, "画像をアップロード", class: "field_btn" %>
              <%= f.file_field :image, class: "file-field" %>
            </div>
            
            <div class="info">
                <h3>ニックネーム</h3>
                <%= f.text_field :nickname, placeholder: "Nickname", class: "edit_nickname" %>
            </div>
          
            <div class="info">
              <%= f.submit "完了", class: "done field_btn" %>
            </div>
        <% end %>
    </div>
</div>

       

app/views/users/show.html.erb
<% provide :title, " | マイページ" %>
<div class="setting">
    <div class="whitecover">
        <div class="card">
                <%= link_to image_tag("neji.png", class: "neji"), edit_user_path(current_user) %>
            <div class="cardinner" >
             <% if current_user.image.attached? %>
             <!--image画像を設定しているか否かで分岐、していない際はこちらから指定-->
                <%= image_tag (current_user.image), class: "top-image" %>
             <% else %>
                <%= image_tag 'Sherlock-Holmes.png', class: "top-image" %>
             <% end %>
            </div>
            <p><%= current_user.nickname %></p>
            <p>本日飲んだコーヒー: <%= @today %>杯</p>
            <p>カフェイン摂取量: 約<%= @today_caffeine %>mg</p>
            <p>CaffeineWithを始めてから飲んだコーヒー: <%= @cups %>杯</p>
        </div>    
            
            
         <div class="full">
            <div class="oneview">
                <%= render partial: "logs/log", collection: @logs %>
            </div>
         </div>
    </div>
</div>

app/views/users/update.html.erb
<div class="bulletin">
    <div class="mini">
            <p>ユーザー情報を更新しました!<p>
            <%= link_to "トップページに戻る", root_path, class: "minibtn" %>
            <%= link_to "マイページへ", user_path(current_user), class: "minibtn" %>
    </div>
</div>